// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fleetforward.proto

package dk.via.fleetforward.gRPC;

public final class Fleetforward {
  private Fleetforward() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dk.via.fleetforward.gRPC.HandlerType}
   */
  public enum HandlerType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HANDLER_UNKNOWN = 0;</code>
     */
    HANDLER_UNKNOWN(0),
    /**
     * <code>HANDLER_COMPANY = 1;</code>
     */
    HANDLER_COMPANY(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HANDLER_UNKNOWN = 0;</code>
     */
    public static final int HANDLER_UNKNOWN_VALUE = 0;
    /**
     * <code>HANDLER_COMPANY = 1;</code>
     */
    public static final int HANDLER_COMPANY_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HandlerType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HandlerType forNumber(int value) {
      switch (value) {
        case 0: return HANDLER_UNKNOWN;
        case 1: return HANDLER_COMPANY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HandlerType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HandlerType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HandlerType>() {
            public HandlerType findValueByNumber(int number) {
              return HandlerType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.getDescriptor().getEnumTypes().get(0);
    }

    private static final HandlerType[] VALUES = values();

    public static HandlerType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HandlerType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dk.via.fleetforward.gRPC.HandlerType)
  }

  /**
   * Protobuf enum {@code dk.via.fleetforward.gRPC.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTION_UNKNOWN = 0;</code>
     */
    ACTION_UNKNOWN(0),
    /**
     * <code>ACTION_CREATE = 1;</code>
     */
    ACTION_CREATE(1),
    /**
     * <code>ACTION_GET = 2;</code>
     */
    ACTION_GET(2),
    /**
     * <code>ACTION_UPDATE = 3;</code>
     */
    ACTION_UPDATE(3),
    /**
     * <code>ACTION_DELETE = 4;</code>
     */
    ACTION_DELETE(4),
    /**
     * <code>ACTION_LIST = 5;</code>
     */
    ACTION_LIST(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACTION_UNKNOWN = 0;</code>
     */
    public static final int ACTION_UNKNOWN_VALUE = 0;
    /**
     * <code>ACTION_CREATE = 1;</code>
     */
    public static final int ACTION_CREATE_VALUE = 1;
    /**
     * <code>ACTION_GET = 2;</code>
     */
    public static final int ACTION_GET_VALUE = 2;
    /**
     * <code>ACTION_UPDATE = 3;</code>
     */
    public static final int ACTION_UPDATE_VALUE = 3;
    /**
     * <code>ACTION_DELETE = 4;</code>
     */
    public static final int ACTION_DELETE_VALUE = 4;
    /**
     * <code>ACTION_LIST = 5;</code>
     */
    public static final int ACTION_LIST_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return ACTION_UNKNOWN;
        case 1: return ACTION_CREATE;
        case 2: return ACTION_GET;
        case 3: return ACTION_UPDATE;
        case 4: return ACTION_DELETE;
        case 5: return ACTION_LIST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.getDescriptor().getEnumTypes().get(1);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dk.via.fleetforward.gRPC.ActionType)
  }

  /**
   * Protobuf enum {@code dk.via.fleetforward.gRPC.StatusType}
   */
  public enum StatusType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    STATUS_UNKNOWN(0),
    /**
     * <code>STATUS_OK = 1;</code>
     */
    STATUS_OK(1),
    /**
     * <code>STATUS_ERROR = 2;</code>
     */
    STATUS_ERROR(2),
    /**
     * <code>STATUS_INVALID_PAYLOAD = 3;</code>
     */
    STATUS_INVALID_PAYLOAD(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    public static final int STATUS_UNKNOWN_VALUE = 0;
    /**
     * <code>STATUS_OK = 1;</code>
     */
    public static final int STATUS_OK_VALUE = 1;
    /**
     * <code>STATUS_ERROR = 2;</code>
     */
    public static final int STATUS_ERROR_VALUE = 2;
    /**
     * <code>STATUS_INVALID_PAYLOAD = 3;</code>
     */
    public static final int STATUS_INVALID_PAYLOAD_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusType forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNKNOWN;
        case 1: return STATUS_OK;
        case 2: return STATUS_ERROR;
        case 3: return STATUS_INVALID_PAYLOAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
            public StatusType findValueByNumber(int number) {
              return StatusType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.getDescriptor().getEnumTypes().get(2);
    }

    private static final StatusType[] VALUES = values();

    public static StatusType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dk.via.fleetforward.gRPC.StatusType)
  }

  public interface CompanyProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.via.fleetforward.gRPC.CompanyProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string mc_number = 2;</code>
     * @return The mcNumber.
     */
    java.lang.String getMcNumber();
    /**
     * <code>string mc_number = 2;</code>
     * @return The bytes for mcNumber.
     */
    com.google.protobuf.ByteString
        getMcNumberBytes();

    /**
     * <code>string company_name = 3;</code>
     * @return The companyName.
     */
    java.lang.String getCompanyName();
    /**
     * <code>string company_name = 3;</code>
     * @return The bytes for companyName.
     */
    com.google.protobuf.ByteString
        getCompanyNameBytes();
  }
  /**
   * Protobuf type {@code dk.via.fleetforward.gRPC.CompanyProto}
   */
  public static final class CompanyProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.via.fleetforward.gRPC.CompanyProto)
      CompanyProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompanyProto.newBuilder() to construct.
    private CompanyProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompanyProto() {
      mcNumber_ = "";
      companyName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CompanyProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompanyProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mcNumber_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              companyName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_CompanyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.class, dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MC_NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object mcNumber_;
    /**
     * <code>string mc_number = 2;</code>
     * @return The mcNumber.
     */
    @java.lang.Override
    public java.lang.String getMcNumber() {
      java.lang.Object ref = mcNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mcNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string mc_number = 2;</code>
     * @return The bytes for mcNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMcNumberBytes() {
      java.lang.Object ref = mcNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mcNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object companyName_;
    /**
     * <code>string company_name = 3;</code>
     * @return The companyName.
     */
    @java.lang.Override
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      }
    }
    /**
     * <code>string company_name = 3;</code>
     * @return The bytes for companyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mcNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mcNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(companyName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, companyName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mcNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mcNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(companyName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, companyName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.via.fleetforward.gRPC.Fleetforward.CompanyProto)) {
        return super.equals(obj);
      }
      dk.via.fleetforward.gRPC.Fleetforward.CompanyProto other = (dk.via.fleetforward.gRPC.Fleetforward.CompanyProto) obj;

      if (getId()
          != other.getId()) return false;
      if (!getMcNumber()
          .equals(other.getMcNumber())) return false;
      if (!getCompanyName()
          .equals(other.getCompanyName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + MC_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMcNumber().hashCode();
      hash = (37 * hash) + COMPANY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.via.fleetforward.gRPC.Fleetforward.CompanyProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.via.fleetforward.gRPC.CompanyProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.via.fleetforward.gRPC.CompanyProto)
        dk.via.fleetforward.gRPC.Fleetforward.CompanyProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_CompanyProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.class, dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.Builder.class);
      }

      // Construct using dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        mcNumber_ = "";

        companyName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.CompanyProto getDefaultInstanceForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.getDefaultInstance();
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.CompanyProto build() {
        dk.via.fleetforward.gRPC.Fleetforward.CompanyProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.CompanyProto buildPartial() {
        dk.via.fleetforward.gRPC.Fleetforward.CompanyProto result = new dk.via.fleetforward.gRPC.Fleetforward.CompanyProto(this);
        result.id_ = id_;
        result.mcNumber_ = mcNumber_;
        result.companyName_ = companyName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.via.fleetforward.gRPC.Fleetforward.CompanyProto) {
          return mergeFrom((dk.via.fleetforward.gRPC.Fleetforward.CompanyProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.via.fleetforward.gRPC.Fleetforward.CompanyProto other) {
        if (other == dk.via.fleetforward.gRPC.Fleetforward.CompanyProto.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getMcNumber().isEmpty()) {
          mcNumber_ = other.mcNumber_;
          onChanged();
        }
        if (!other.getCompanyName().isEmpty()) {
          companyName_ = other.companyName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.via.fleetforward.gRPC.Fleetforward.CompanyProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.via.fleetforward.gRPC.Fleetforward.CompanyProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mcNumber_ = "";
      /**
       * <code>string mc_number = 2;</code>
       * @return The mcNumber.
       */
      public java.lang.String getMcNumber() {
        java.lang.Object ref = mcNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mcNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mc_number = 2;</code>
       * @return The bytes for mcNumber.
       */
      public com.google.protobuf.ByteString
          getMcNumberBytes() {
        java.lang.Object ref = mcNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mcNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mc_number = 2;</code>
       * @param value The mcNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMcNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mcNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mc_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMcNumber() {
        
        mcNumber_ = getDefaultInstance().getMcNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string mc_number = 2;</code>
       * @param value The bytes for mcNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMcNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mcNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object companyName_ = "";
      /**
       * <code>string company_name = 3;</code>
       * @return The companyName.
       */
      public java.lang.String getCompanyName() {
        java.lang.Object ref = companyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          companyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company_name = 3;</code>
       * @return The bytes for companyName.
       */
      public com.google.protobuf.ByteString
          getCompanyNameBytes() {
        java.lang.Object ref = companyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company_name = 3;</code>
       * @param value The companyName to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompanyName() {
        
        companyName_ = getDefaultInstance().getCompanyName();
        onChanged();
        return this;
      }
      /**
       * <code>string company_name = 3;</code>
       * @param value The bytes for companyName to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        companyName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.via.fleetforward.gRPC.CompanyProto)
    }

    // @@protoc_insertion_point(class_scope:dk.via.fleetforward.gRPC.CompanyProto)
    private static final dk.via.fleetforward.gRPC.Fleetforward.CompanyProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.via.fleetforward.gRPC.Fleetforward.CompanyProto();
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.CompanyProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompanyProto>
        PARSER = new com.google.protobuf.AbstractParser<CompanyProto>() {
      @java.lang.Override
      public CompanyProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompanyProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompanyProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompanyProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.via.fleetforward.gRPC.Fleetforward.CompanyProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.via.fleetforward.gRPC.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
     * @return The enum numeric value on the wire for handler.
     */
    int getHandlerValue();
    /**
     * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
     * @return The handler.
     */
    dk.via.fleetforward.gRPC.Fleetforward.HandlerType getHandler();

    /**
     * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
     * @return The action.
     */
    dk.via.fleetforward.gRPC.Fleetforward.ActionType getAction();

    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.Any getPayload();
    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code dk.via.fleetforward.gRPC.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.via.fleetforward.gRPC.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      handler_ = 0;
      action_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              handler_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (payload_ != null) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.fleetforward.gRPC.Fleetforward.Request.class, dk.via.fleetforward.gRPC.Fleetforward.Request.Builder.class);
    }

    public static final int HANDLER_FIELD_NUMBER = 1;
    private int handler_;
    /**
     * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
     * @return The enum numeric value on the wire for handler.
     */
    @java.lang.Override public int getHandlerValue() {
      return handler_;
    }
    /**
     * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
     * @return The handler.
     */
    @java.lang.Override public dk.via.fleetforward.gRPC.Fleetforward.HandlerType getHandler() {
      @SuppressWarnings("deprecation")
      dk.via.fleetforward.gRPC.Fleetforward.HandlerType result = dk.via.fleetforward.gRPC.Fleetforward.HandlerType.valueOf(handler_);
      return result == null ? dk.via.fleetforward.gRPC.Fleetforward.HandlerType.UNRECOGNIZED : result;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
     * @return The action.
     */
    @java.lang.Override public dk.via.fleetforward.gRPC.Fleetforward.ActionType getAction() {
      @SuppressWarnings("deprecation")
      dk.via.fleetforward.gRPC.Fleetforward.ActionType result = dk.via.fleetforward.gRPC.Fleetforward.ActionType.valueOf(action_);
      return result == null ? dk.via.fleetforward.gRPC.Fleetforward.ActionType.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.Any payload_;
    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return payload_ != null;
    }
    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.Any getPayload() {
      return payload_ == null ? com.google.protobuf.Any.getDefaultInstance() : payload_;
    }
    /**
     * <code>.google.protobuf.Any payload = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getPayloadOrBuilder() {
      return getPayload();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (handler_ != dk.via.fleetforward.gRPC.Fleetforward.HandlerType.HANDLER_UNKNOWN.getNumber()) {
        output.writeEnum(1, handler_);
      }
      if (action_ != dk.via.fleetforward.gRPC.Fleetforward.ActionType.ACTION_UNKNOWN.getNumber()) {
        output.writeEnum(2, action_);
      }
      if (payload_ != null) {
        output.writeMessage(3, getPayload());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (handler_ != dk.via.fleetforward.gRPC.Fleetforward.HandlerType.HANDLER_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, handler_);
      }
      if (action_ != dk.via.fleetforward.gRPC.Fleetforward.ActionType.ACTION_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (payload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPayload());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.via.fleetforward.gRPC.Fleetforward.Request)) {
        return super.equals(obj);
      }
      dk.via.fleetforward.gRPC.Fleetforward.Request other = (dk.via.fleetforward.gRPC.Fleetforward.Request) obj;

      if (handler_ != other.handler_) return false;
      if (action_ != other.action_) return false;
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HANDLER_FIELD_NUMBER;
      hash = (53 * hash) + handler_;
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.via.fleetforward.gRPC.Fleetforward.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.via.fleetforward.gRPC.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.via.fleetforward.gRPC.Request)
        dk.via.fleetforward.gRPC.Fleetforward.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.via.fleetforward.gRPC.Fleetforward.Request.class, dk.via.fleetforward.gRPC.Fleetforward.Request.Builder.class);
      }

      // Construct using dk.via.fleetforward.gRPC.Fleetforward.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        handler_ = 0;

        action_ = 0;

        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Request_descriptor;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Request getDefaultInstanceForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.Request.getDefaultInstance();
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Request build() {
        dk.via.fleetforward.gRPC.Fleetforward.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Request buildPartial() {
        dk.via.fleetforward.gRPC.Fleetforward.Request result = new dk.via.fleetforward.gRPC.Fleetforward.Request(this);
        result.handler_ = handler_;
        result.action_ = action_;
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.via.fleetforward.gRPC.Fleetforward.Request) {
          return mergeFrom((dk.via.fleetforward.gRPC.Fleetforward.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.via.fleetforward.gRPC.Fleetforward.Request other) {
        if (other == dk.via.fleetforward.gRPC.Fleetforward.Request.getDefaultInstance()) return this;
        if (other.handler_ != 0) {
          setHandlerValue(other.getHandlerValue());
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.via.fleetforward.gRPC.Fleetforward.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.via.fleetforward.gRPC.Fleetforward.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int handler_ = 0;
      /**
       * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
       * @return The enum numeric value on the wire for handler.
       */
      @java.lang.Override public int getHandlerValue() {
        return handler_;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
       * @param value The enum numeric value on the wire for handler to set.
       * @return This builder for chaining.
       */
      public Builder setHandlerValue(int value) {
        
        handler_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
       * @return The handler.
       */
      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.HandlerType getHandler() {
        @SuppressWarnings("deprecation")
        dk.via.fleetforward.gRPC.Fleetforward.HandlerType result = dk.via.fleetforward.gRPC.Fleetforward.HandlerType.valueOf(handler_);
        return result == null ? dk.via.fleetforward.gRPC.Fleetforward.HandlerType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
       * @param value The handler to set.
       * @return This builder for chaining.
       */
      public Builder setHandler(dk.via.fleetforward.gRPC.Fleetforward.HandlerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        handler_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.HandlerType handler = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHandler() {
        
        handler_ = 0;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
       * @return The action.
       */
      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.ActionType getAction() {
        @SuppressWarnings("deprecation")
        dk.via.fleetforward.gRPC.Fleetforward.ActionType result = dk.via.fleetforward.gRPC.Fleetforward.ActionType.valueOf(action_);
        return result == null ? dk.via.fleetforward.gRPC.Fleetforward.ActionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(dk.via.fleetforward.gRPC.Fleetforward.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.ActionType action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any payload_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> payloadBuilder_;
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return payloadBuilder_ != null || payload_ != null;
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       * @return The payload.
       */
      public com.google.protobuf.Any getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.google.protobuf.Any.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public Builder setPayload(com.google.protobuf.Any value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public Builder setPayload(
          com.google.protobuf.Any.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public Builder mergePayload(com.google.protobuf.Any value) {
        if (payloadBuilder_ == null) {
          if (payload_ != null) {
            payload_ =
              com.google.protobuf.Any.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public com.google.protobuf.Any.Builder getPayloadBuilder() {
        
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.google.protobuf.Any payload = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.via.fleetforward.gRPC.Request)
    }

    // @@protoc_insertion_point(class_scope:dk.via.fleetforward.gRPC.Request)
    private static final dk.via.fleetforward.gRPC.Fleetforward.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.via.fleetforward.gRPC.Fleetforward.Request();
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.via.fleetforward.gRPC.Fleetforward.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dk.via.fleetforward.gRPC.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
     * @return The status.
     */
    dk.via.fleetforward.gRPC.Fleetforward.StatusType getStatus();

    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.Any getPayload();
    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code dk.via.fleetforward.gRPC.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dk.via.fleetforward.gRPC.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (payload_ != null) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.fleetforward.gRPC.Fleetforward.Response.class, dk.via.fleetforward.gRPC.Fleetforward.Response.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public dk.via.fleetforward.gRPC.Fleetforward.StatusType getStatus() {
      @SuppressWarnings("deprecation")
      dk.via.fleetforward.gRPC.Fleetforward.StatusType result = dk.via.fleetforward.gRPC.Fleetforward.StatusType.valueOf(status_);
      return result == null ? dk.via.fleetforward.gRPC.Fleetforward.StatusType.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.Any payload_;
    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return payload_ != null;
    }
    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.Any getPayload() {
      return payload_ == null ? com.google.protobuf.Any.getDefaultInstance() : payload_;
    }
    /**
     * <code>.google.protobuf.Any payload = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getPayloadOrBuilder() {
      return getPayload();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != dk.via.fleetforward.gRPC.Fleetforward.StatusType.STATUS_UNKNOWN.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (payload_ != null) {
        output.writeMessage(2, getPayload());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != dk.via.fleetforward.gRPC.Fleetforward.StatusType.STATUS_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (payload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPayload());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dk.via.fleetforward.gRPC.Fleetforward.Response)) {
        return super.equals(obj);
      }
      dk.via.fleetforward.gRPC.Fleetforward.Response other = (dk.via.fleetforward.gRPC.Fleetforward.Response) obj;

      if (status_ != other.status_) return false;
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dk.via.fleetforward.gRPC.Fleetforward.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dk.via.fleetforward.gRPC.Fleetforward.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dk.via.fleetforward.gRPC.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dk.via.fleetforward.gRPC.Response)
        dk.via.fleetforward.gRPC.Fleetforward.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dk.via.fleetforward.gRPC.Fleetforward.Response.class, dk.via.fleetforward.gRPC.Fleetforward.Response.Builder.class);
      }

      // Construct using dk.via.fleetforward.gRPC.Fleetforward.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.internal_static_dk_via_fleetforward_gRPC_Response_descriptor;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Response getDefaultInstanceForType() {
        return dk.via.fleetforward.gRPC.Fleetforward.Response.getDefaultInstance();
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Response build() {
        dk.via.fleetforward.gRPC.Fleetforward.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.Response buildPartial() {
        dk.via.fleetforward.gRPC.Fleetforward.Response result = new dk.via.fleetforward.gRPC.Fleetforward.Response(this);
        result.status_ = status_;
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dk.via.fleetforward.gRPC.Fleetforward.Response) {
          return mergeFrom((dk.via.fleetforward.gRPC.Fleetforward.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dk.via.fleetforward.gRPC.Fleetforward.Response other) {
        if (other == dk.via.fleetforward.gRPC.Fleetforward.Response.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dk.via.fleetforward.gRPC.Fleetforward.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dk.via.fleetforward.gRPC.Fleetforward.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public dk.via.fleetforward.gRPC.Fleetforward.StatusType getStatus() {
        @SuppressWarnings("deprecation")
        dk.via.fleetforward.gRPC.Fleetforward.StatusType result = dk.via.fleetforward.gRPC.Fleetforward.StatusType.valueOf(status_);
        return result == null ? dk.via.fleetforward.gRPC.Fleetforward.StatusType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(dk.via.fleetforward.gRPC.Fleetforward.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dk.via.fleetforward.gRPC.StatusType status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any payload_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> payloadBuilder_;
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return payloadBuilder_ != null || payload_ != null;
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       * @return The payload.
       */
      public com.google.protobuf.Any getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.google.protobuf.Any.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.Any value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public Builder setPayload(
          com.google.protobuf.Any.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public Builder mergePayload(com.google.protobuf.Any value) {
        if (payloadBuilder_ == null) {
          if (payload_ != null) {
            payload_ =
              com.google.protobuf.Any.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public com.google.protobuf.Any.Builder getPayloadBuilder() {
        
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.google.protobuf.Any payload = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dk.via.fleetforward.gRPC.Response)
    }

    // @@protoc_insertion_point(class_scope:dk.via.fleetforward.gRPC.Response)
    private static final dk.via.fleetforward.gRPC.Fleetforward.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dk.via.fleetforward.gRPC.Fleetforward.Response();
    }

    public static dk.via.fleetforward.gRPC.Fleetforward.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dk.via.fleetforward.gRPC.Fleetforward.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_fleetforward_gRPC_CompanyProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_fleetforward_gRPC_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_fleetforward_gRPC_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_fleetforward_gRPC_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_fleetforward_gRPC_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022fleetforward.proto\022\030dk.via.fleetforwar" +
      "d.gRPC\032\031google/protobuf/any.proto\"C\n\014Com" +
      "panyProto\022\n\n\002id\030\001 \001(\005\022\021\n\tmc_number\030\002 \001(\t" +
      "\022\024\n\014company_name\030\003 \001(\t\"\236\001\n\007Request\0226\n\007ha" +
      "ndler\030\001 \001(\0162%.dk.via.fleetforward.gRPC.H" +
      "andlerType\0224\n\006action\030\002 \001(\0162$.dk.via.flee" +
      "tforward.gRPC.ActionType\022%\n\007payload\030\003 \001(" +
      "\0132\024.google.protobuf.Any\"g\n\010Response\0224\n\006s" +
      "tatus\030\001 \001(\0162$.dk.via.fleetforward.gRPC.S" +
      "tatusType\022%\n\007payload\030\002 \001(\0132\024.google.prot" +
      "obuf.Any*7\n\013HandlerType\022\023\n\017HANDLER_UNKNO" +
      "WN\020\000\022\023\n\017HANDLER_COMPANY\020\001*z\n\nActionType\022" +
      "\022\n\016ACTION_UNKNOWN\020\000\022\021\n\rACTION_CREATE\020\001\022\016" +
      "\n\nACTION_GET\020\002\022\021\n\rACTION_UPDATE\020\003\022\021\n\rACT" +
      "ION_DELETE\020\004\022\017\n\013ACTION_LIST\020\005*]\n\nStatusT" +
      "ype\022\022\n\016STATUS_UNKNOWN\020\000\022\r\n\tSTATUS_OK\020\001\022\020" +
      "\n\014STATUS_ERROR\020\002\022\032\n\026STATUS_INVALID_PAYLO" +
      "AD\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_via_fleetforward_gRPC_CompanyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_fleetforward_gRPC_CompanyProto_descriptor,
        new java.lang.String[] { "Id", "McNumber", "CompanyName", });
    internal_static_dk_via_fleetforward_gRPC_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_via_fleetforward_gRPC_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_fleetforward_gRPC_Request_descriptor,
        new java.lang.String[] { "Handler", "Action", "Payload", });
    internal_static_dk_via_fleetforward_gRPC_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dk_via_fleetforward_gRPC_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_fleetforward_gRPC_Response_descriptor,
        new java.lang.String[] { "Status", "Payload", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
